services:
  app:
    image: ghcr.io/snow-platform/portfolio-ui:${VERSION}
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    cpu_count: 1
    mem_limit: 512M
    mem_reservation: 256M
