name: release-retry.yml

on: workflow_call

jobs:
  upload:
    uses: ./.github/workflows/prerelease.yml

  deploy:
    needs: upload
    runs-on: desperation
    steps:
      - uses: actions/checkout@v6
      - name: compose up
        run: docker compose up -d
